import { StyleSheet } from 'react-native';
export const TimerStyles = StyleSheet.create({
  timerContainer: {
    marginTop: 50,
    width: 320,
    height: 320,
    borderRadius: 160,
    justifyContent: 'center',
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#151414',
    borderEndWidth: 2,
    borderStartWidth: 2,
    borderStartColor: 'cyan',
    borderEndColor: 'cyan',
    shadowColor: '#0c72ab',
    elevation: 60,
    position: 'relative',
  },
  mainContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerFont: {
    fontFamily: 'Orbitron_500Medium',
    fontSize: 50,
    position: 'absolute',
    color: 'white',
  },
  btnContainer: {
    display: 'flex',
    justifyContent: 'center',
    borderRadius: 40,
    marginLeft: 10,
    marginRight: 10,
    padding: 10,
    elevation: 10,
    shadowColor: '#333b47',
  },
  btnContainerPlay: {
    display: 'flex',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRadius: 40,
    marginLeft: 10,
    marginRight: 10,
    elevation: 10,
    padding: 10,
    shadowColor: '#333b47',
  },
  iconsContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 60,
    marginBottom: 50,
  },
  gradient: {
    borderRadius: 50,
    padding: 5,
  },
});
