import { StyleSheet } from 'react-native';
export const TimerStyles = StyleSheet.create({
  timerContainer: {
    marginTop: 50,
    width: 320,
    height: 320,
    borderRadius: 160,
    justifyContent: 'center',
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#000814',
    borderEndWidth: 2,
    borderStartWidth: 2,
    borderStartColor: '#949494',
    borderEndColor: '#949494',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 8,
      height: 8,
    },
    shadowOpacity: 0.4,
    shadowRadius: 11,
  },
  mainContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerFont: {
    fontFamily: 'Orbitron_500Medium',
    fontSize: 50,
  },
  btnContainer: {
    display: 'flex',
    justifyContent: 'center',
    backgroundColor: '#F7E8E1',
    borderRadius: 40,
    marginLeft: 10,
    marginRight: 10,
    borderWidth: 1,
    padding: 5,
  },
  btnContainerPlay: {
    display: 'flex',
    justifyContent: 'center',
    backgroundColor: '#F7E8E1',
    borderRadius: 40,
    marginLeft: 10,
    marginRight: 10,
    borderWidth: 1,
    padding: 5,
  },
  iconsContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 60,
    marginBottom: 50,
  },
});
